cactusapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogue/', include('catalogue.urls')),
    path('', TemplateView.as_view(template_name="default.html"), name="default"),

]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogue/urls.py
from django.urls import path

from . import views
from . import api

urlpatterns = [
    path('', views.index, name='index'),
    path('maps/', views.map, name='map'),
    path('species/', views.SpeciesListView.as_view(), name='species'),
    path('species/scrape/', views.speciesfromurl, name='speciesfromurl'),
    path('species/<int:pk>', views.SpeciesDetailView.as_view(), name='species-detail'),
]

urlpatterns += [  
    path('species/create/', views.SpeciesCreate.as_view(), name='species-create'),
    path('species/update/', views.speciesgrid, name='species-update-all'),
    path('species/<int:pk>/location/', views.SpeciesAddLocationView.as_view(), name='species-add-location'),
    path('species/<int:pk>/location/success/', views.SpeciesAddLocationSuccView.as_view(), name='species-add-location-success'),
    path('species/<int:pk>/update/', views.SpeciesUpdate.as_view(), name='species-update'),
    path('species/<int:pk>/delete/', views.SpeciesDelete.as_view(), name='species-delete'),
    path('sources/', views.SourceListView.as_view(), name='sources'),
    path('sources/labels/', views.SourceLabelsView.as_view(), name='source-labels'),
    path('source/<int:pk>', views.SourceDetailView.as_view(), name='source-detail'),
    path('source/<int:pk>/label/', views.SourceLabelView.as_view(), name='source-label'),
    path('source/create/', views.SourceCreate.as_view(), name='source-create'),
    path('sources/update/', views.sourcegrid, name='sources-update'),
    path('source/<int:pk>/update/', views.SourceUpdate.as_view(), name='source-update'),
    path('source/<int:pk>/delete/', views.SourceDelete.as_view(), name='source-delete'),
    path('source/uuid/<uuid:uuid>', views.SourceUUIDView.as_view(), name='source-uuid'),

]

urlpatterns += [  
    path('therm/push/', views.add_therm, name='add-therm'),
    path('api/loggers/', api.AllLoggers.as_view(), name='api-loggers'),
    path('loggers/dashboard/', views.logger_dashboard, name='loggers-dashboard'),
    path('loggers/data/', views.LoggerDataListView.as_view(), name='loggers-data'),
]

catalogue/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from djangoyearlessdate.models import YearlessDateField
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User
from django.core import files
import django_filters
import imghdr # Used to validate images
import urllib # Used to download images
import requests, datetime
import tempfile
import io
from PIL import Image # Holds downloaded image and verifies it
import copy # Copies instances of Image
from datetime import date
import uuid # Required for unique uuids
from django.utils import timezone

from versatileimagefield.fields import VersatileImageField, PPOIField
from geoposition.fields import GeopositionField

class Photo(models.Model):
    image = VersatileImageField(
        'Image',
        upload_to='images/',
        width_field='width',
        height_field='height',
        blank=True,
        null=True
    )
    caption = models.CharField(
        'Caption',
        max_length=80
    )
    height = models.PositiveIntegerField(
        'Image Height',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Image Width',
        blank=True,
        null=True
    )
    created = models.DateTimeField(editable=False)
    image_url = models.URLField(null=True, blank=True)
    order = models.PositiveIntegerField(default=1)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        ordering = ['order']

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        if (self.image_url != None):
            url = self.image_url
            image_file = download_image(url) # See function definition below
            try:
                filename = urllib.parse.urlparse(url).path.split('/')[-1]
                self.image.save(filename, image_file, save=False) # Set save=False otherwise you will have a looping save method
            except Exception as e:
                print ("Error trying to save model: saving image failed: " + str(e))
                pass
        super(Photo, self).save(*args, **kwargs) # We've gotten the image into the ImageField above...now we actually need to save it. We've redefined the save method for Product, so super *should* get the parent of class Product, models.Model and then run IT'S save method, which will save the Product like normal
        
    def __str__(self):
        return f'{self.id} : {self.image_url}  -  ({self.caption})'

def download_image(url):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0'} # More likely to get a response if server thinks you're a browser
    response = requests.get(url, stream=True)    
    # Create a temporary file
    lf = tempfile.NamedTemporaryFile()
    # Read the streamed image in sections
    for block in response.iter_content(1024 * 8):
        # If no more file then stop
        if not block:
            break
        # Write image block to temporary file
        lf.write(block)
    img = files.File(lf)

    return img
        
def valid_img(img):
    type = img.format
    if type in ('GIF', 'JPEG', 'JPG', 'PNG'):
        try:
            img.verify()
            return True
        except:
            return False
    else: return False

DIFFICULTY_LEVELS = [
        ('VERY_EASY', 'Very easy'),
        ('EASY', 'Easy'),
        ('AVERAGE', 'Average'),
        ('SOME_DIFFICULTY', 'Some difficulty'),
        ('DIFFICULT', 'Difficult'),
        ('VERY_DIFFICULT', 'Very difficult'),
    ]    

class Species(models.Model):
    scientific_name = models.CharField(max_length=200, help_text='Enter the scientific name for this species')
    family = models.CharField(max_length=200, null=True, blank=True)
    author = models.CharField(max_length=200, null=True, blank=True)
    source = models.CharField(max_length=200, null=True, blank=True)
    genus = models.CharField(max_length=200, null=True, blank=True)
    subgenus = models.CharField(max_length=200, null=True, blank=True)
    specific_epithet = models.CharField(max_length=200, null=True, blank=True)
    origin = models.CharField(max_length=200, null=True, blank=True)
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_LEVELS, default='AVERAGE')
    growing_season_start = YearlessDateField(null=True, blank=True)
    growing_season_end = YearlessDateField(null=True, blank=True)
    min_temp_c = models.FloatField(null=True, blank=True)
    max_temp_c = models.FloatField(null=True, blank=True)
    light = models.CharField(max_length=200, null=True, blank=True)
    watering = models.CharField(max_length=200, null=True, blank=True)
    humidity = models.CharField(max_length=200, null=True, blank=True)
    substrate = models.CharField(max_length=200, null=True, blank=True)
    url = models.URLField(max_length=200, null=True, blank=True)
    photos = GenericRelation(Photo, related_query_name='species')

    def __str__(self):
        return self.scientific_name
    
    def get_absolute_url(self):
        return reverse('species-detail', args=[str(self.id)])
    
    def primary_image(self):
        primary = Photo.objects.filter(species=self).first()
        return primary.image.crop["300x300"]

    def location_count(self):
        location_count = Location.objects.filter(species=self).count()
        return location_count
    
    def primary(self):
        primary = Photo.objects.filter(species=self).first()
        return primary

    class Meta:
        verbose_name_plural = "Species"
        ordering = ['scientific_name']

class Location(models.Model):
    name = models.CharField(max_length=100)
    position = GeopositionField()
    species = models.ForeignKey(Species, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class SpeciesDescription(models.Model):
    description = models.CharField(max_length=4000)
    descript_type = models.CharField(max_length=100)
    descript_group = models.CharField(max_length=100, null=True, blank=True)
    order = models.PositiveIntegerField(default=1)
    species = models.ForeignKey('Species', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.descript_type}: {self.description}'

class CommonName(models.Model):
    common_name = models.CharField(max_length=200)
    meaning = models.CharField(max_length=500)
    species = models.ForeignKey('Species', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.common_name

STATUSES = [
        ('PENDING', 'Pending'),
        ('SOWN', 'Sown'),
        ('ACTIVE', 'Active'),
        ('NO_RESULTS', 'No results'),
        ('NON-ARRIVAL', 'Did not arrive'),
    ]

class SoilType(models.Model):
    composition = models.CharField(max_length=300)
    treatment = models.CharField(max_length=300)
    
    def __str__(self):
        return self.composition

class Source(models.Model):
    name = models.CharField(max_length=200)
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, unique=True, editable=False)
    species = models.ForeignKey('Species', on_delete=models.SET_NULL, null=True, blank=True, related_name='sources') 
    seed_count = models.IntegerField()
    obtained_from = models.CharField(max_length=100)
    purchase_date = models.DateField(null=True, blank=True)
    supplier_reference = models.CharField(max_length=50)
    note = models.CharField(max_length=1000, null=True, blank=True)
    cost = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    date_sown = models.DateField(null=True, blank=True, help_text='Date acquired, or date sown if from seed.')
    sowing_method = models.CharField(max_length=300, null=True, blank=True)
    ten_day_count = models.IntegerField(null=True, blank=True)
    end_count = models.IntegerField(null=True, blank=True)
    soil_type = models.ForeignKey('SoilType', on_delete=models.SET_NULL, null=True, blank=True, related_name='sources') 
    photos = GenericRelation(Photo, related_query_name='source')

    status = models.CharField(max_length=20, choices=STATUSES, default='PENDING')

    def get_absolute_url(self):
        return reverse('source-detail', args=[str(self.id)])

    def primary_image(self):
        primary = Photo.objects.filter(source=self).order_by('-created').first()
        return primary.image.crop["300x300"]

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class F(django_filters.FilterSet):
    status = django_filters.ChoiceFilter(choices=STATUSES)
    class Meta:
        model = Source
        fields = ['status']

class LoggerData(models.Model):
    device_id = models.CharField(max_length=100)
    temperature = models.FloatField(null=True, blank=True)
    humidity = models.FloatField(null=True, blank=True)
    lux = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField()

    def nearest_timestamp(self, roundTo=60*5):
        """Round a datetime object to any time lapse in seconds
        dt : datetime.datetime object.
        roundTo : Closest number of seconds to round to, default 1 minute.
        """
        dt = self.timestamp
        seconds = (dt.replace(tzinfo=None) - dt.min).seconds
        rounding = (seconds+roundTo/2) // roundTo * roundTo
        print(dt + datetime.timedelta(0,rounding-seconds,-dt.microsecond))
        return dt + datetime.timedelta(0,rounding-seconds,-dt.microsecond)

    class Meta:
        ordering = ['device_id', '-timestamp']
    

catalogue/templates/catalogue/labels.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>     
        @page {
            margin: 0;
            size: 10cm  1.9cm;
        }
        body {
            margin: 0;
        }
        html {
        align-content: space-around;
        align-items: flex-start;
        background: #eef1f5;
        display: flex;
        font-family: Barlow Condensed, sans-serif;
        height: 100%;
        justify-content: center;
        }
        .page {
        background: #fff;
        page-break-after: always;
        box-sizing: border-box;
        display: flex;
        flex-direction: column;
        align-content: flex-start;
        flex-wrap: wrap;
        justify-content: flex-start;
        height: 1.9cm;
        margin: 0;
        width: 10cm;
        }
        section {
        box-sizing: border-box;
        }
        #label {
        display: flex;
        flex-direction: column;
        height: 1.9cm;
        justify-content: center;
        padding: 0 .6cm;
        }
        #label .row {
        display: inline-block;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif, cursive;
        font-size: 9pt;
        margin-left: 1px;
        max-width: 6cm;
        
        }
        #label .row#mainlabel {
            font-size: 9pt;
        }
        #label .row#secondarylabel {
            font-size: 8pt;
        }
        img {
            position: relative;
            z-index: 10;
            right: 60px;
            max-width: 40px;
            max-height: 40px;
            width: auto;
            margin-right: 65px;
            height: auto;
            }
    </style>
</head>
        <body>
            {% for source in sources %}
            <div class="page">
                <section id="label">
                  <div class="row" id="mainlabel"><strong>{{source.name}}</strong></div>
                  <div class="row" id="secondarylabel"><label>{{ source.obtained_from }}{% if source.supplier_reference %} ({{source.supplier_reference}}){% endif %} {{source.seed_count}} X {% if source.date_sown %} Sown on {{source.date_sown}}{% endif %}</label></div>
                </section>
            </div>
            {% endfor %}
        </body>
</html>

catalogue/templates/catalogue/logger_dashboard.html
{% extends "base_generic.html" %}
{% load static %}
{% load bootstrap3 %}
{% block content %} 

<div class="row">
    {% if filter %}
        <form action="" method="get" class="form form-inline" style="padding-left:10px; padding-right:10px;">
            {% bootstrap_form filter.form %}
            {% bootstrap_button 'filter' %}
        </form>
    {% endif %}
  </div>
<div class="row">
    <div class="col-md-12">
            <canvas id="loggerChart1" width="800" height="300"></canvas>
    </div>
</div>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.bundle.js"></script><script type="text/javascript">

    var config = {
        type: 'line',
        data: {
            labels: {{ labels|safe }},
            datasets: {{ datasets|safe }},
        },
        options: {
            responsive: true,
            scales: {
                xAxes: [
                {
                    type: "time",
                    time: {
                        displayFormats: {
                            'minute': 'YYYY-MM-DD  HH:mm',
                            'hour': 'YYYY-MM-DD  HH:mm',
                            'day': 'YYYY-MM-DD  HH:mm',
                            'month': 'YYYY-MM-DD  HH:mm',
                            'year': 'YYYY-MM-DD  HH:mm',
                    }
                    },
                    ticks: {
                        autoSkip: true,
                        maxTicksLimit: 20
                    }
                }
                ]
            }
        }
    };
    window.onload = function() {
        var ctx = document.getElementById('loggerChart1').getContext('2d');;
        window.myPie = new Chart(ctx, config);
        
    };      
    
</script>
<style>
    .form-inline label {
       font-weight: bold;
     }
 
   .form-inline .form-group {
       flex-direction: column;
       align-items: flex-start;
     }
</style>
{% endblock content %}

catalogue/templates/catalogue/logger_data_list.html
{% extends "base_generic.html" %}

{% block content %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
  <div class="card">
      <div class="card-header">
          Logger Data
      </div>
      <div class="card-body">
        <div class="row">
          {% if filter %}
              <form action="" method="get" class="form form-inline" style="padding-left:10px;">
                  {% bootstrap_form filter.form %}
                  {% bootstrap_button 'filter' %}
              </form>
          {% endif %}
        </div>
        <div class="container" style="padding-top:20px;">
          {% render_table table %}
        </div>
        
      </div>
  </div>

  <style>
    .form-inline label {
       font-weight: bold;
     }
 
   .form-inline .form-group {
       flex-direction: column;
       align-items: flex-start;
     }
  </style>
 
{% endblock %}

catalogue/templates/catalogue/map_test.html
{% extends "base_generic.html" %}
{% block content %}

  <div class="card">
      <div class="card-body">
        <div class="container">
          <div id="map" style="width: 1000px; height: 1000px;"></div>
        </div>
      </div>
  </div>
  <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyDkrygpZXzJxvajC9zqbv5eKT6HFZqLx5U"></script>

  
{% endblock %}
  

  

catalogue/templates/catalogue/scrape.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<div class="container">
    <div class="card">
        <div class="card-header">
            Create Species from Llifle.com URL
        </div>
        <div class="card-body">
            <form method = "post" enctype="multipart/form-data">
             {% crispy form %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}

catalogue/templates/catalogue/source_create.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            {% if 'update' in request.resolver_match.url_name %}Update {% else %}New {% endif %}Source
        </div>
        <div class="card-body">
            <form method = "post" enctype="multipart/form-data">
             {% crispy form %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}

catalogue/templates/catalogue/source_detail.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-md-12" style="margin-bottom:20px;">
          {% if pagination.prev %}
          <a class="btn btn-secondary float-left" href="{% url 'source-detail' pagination.prev.pk %}" role="button">Previous</a>
          {% endif %}
          {% if pagination.next %}
          <a class="btn btn-secondary float-right" href="{% url 'source-detail' pagination.next.pk %}" role="button">Next</a>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <h1><b>{{ source.name }}</b> </h1>
        </div>
        <div class="col-md-3">
          <h2>
            <button type="button" class="btn btn-outline-danger float-left">
              <a href="{% url 'source-delete' source.pk %}">Delete Source</a>
            </button>
            <button type="button" class="btn btn-outline-primary float-right">
              <a href="{% url 'source-update' source.pk %}">Edit Source</a>
            </button>
          </h2>
        </div>
      </div>
      {% if source.species %}
          <h4><a href="{% url 'species-detail' source.species.pk %}"><i>{{ source.species }}</i></a></h4>
      {% else %}
          <h4><a><i>{{ source.species }}</i></a></h4>
      {% endif %}
      <h6>{{ source.uuid }}</h6>
    </div>
    <div class="card-body">
      <div class="row">
          <div class="col-md-4">
            <p><strong>Seed count:</strong> {{ source.seed_count }}</p>
            <p><strong>End count:</strong> {{ source.end_count }}</p>
          </div>
          <div class="col-md-4">
            <p><strong>Obtained from:</strong> {{ source.obtained_from }}</p>
            <p><strong>Cost:</strong> £ {{ source.cost }}</p>
          </div>
          <div class="col-md-4">
            <p><strong>Purchase date:</strong> {{ source.purchase_date }}</p>
            <p><strong>Supplier reference:</strong> {{ source.supplier_reference}}</p>
          </div>
      </div>
      <div class="row">
          <div class="col-md-4">
            <p><strong>Sowing date:</strong> {{ source.date_sown }}</p>
          </div>
          <div class="col-md-4">
            <p><strong>Status:</strong> {{ source.get_status_display }}</p>
          </div>
          <div class="col-md-4">
            <p><strong>Sowing method:</strong> {{ source.sowing_method }}</p>
            <p><strong>Soil type:</strong> {{ source.soil_type }}</p>
          </div>
      </div>
      
      {% if not source.species %}
      <div class="row">
        <div class="col-md-12">
          <form method = "post" enctype="multipart/form-data">
            {% crispy form %}
           </form>
        </div>
      </div>
      {% endif %}

      <div class="row justify-content-center" style="margin-left:20px;margin-right:20px;margin-top:10px;">
        {% for photo in source.photos.all %}
          <div class="card" style="width: 15rem;">
            <a href ="/media/{{ photo.image }}"><img class="card-img-top" src="{{ photo.image.crop.200x200 }}"  alt="Card image cap"></a>
            <div class="card-body">
              <p style="width: 100%; text-align: center;"><small><i>{{ photo.caption }}</i></small></p>
            </div>
          </div>
          {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row justify-content-center" style="margin-left:20px;margin-right:20px;margin-top:10px;">
          {% endif %}
        {% endfor %}
      </div>
      <div class="row justify-content-center" style="margin-left:20px;margin-right:20px;margin-top:10px;">
        {% for photo in source.species.photos.all %}
          <div class="card" style="width: 15rem;">
            <a href ="/media/{{ photo.image }}"><img class="card-img-top" src="{{ photo.image.crop.200x200 }}"  alt="Card image cap"></a>
            <div class="card-body">
              <p style="width: 100%; text-align: center;"><small><i>{{ photo.caption }}</i></small></p>
            </div>
          </div>
          {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row justify-content-center" style="margin-left:20px;margin-right:20px;margin-top:10px;">
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalogue/templates/catalogue/species_detail.html
{% extends "base_generic.html" %}
{% block content %}
<div class="container">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-md-12" style="margin-bottom:20px;">
          {% if pagination.prev %}
          <a class="btn btn-secondary float-left" href="{% url 'species-detail' pagination.prev.pk %}" role="button">Previous</a>
          {% endif %}
          {% if pagination.next %}
          <a class="btn btn-secondary float-right" href="{% url 'species-detail' pagination.next.pk %}" role="button">Next</a>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <h1><b>{{ species.scientific_name }}</b>
        </div>
        <div class="col-md-4">
            <a class="btn btn-outline-danger float-left" href="{% url 'species-delete' species.pk %}" role="button">Delete Species</a>
            <a class="btn btn-outline-primary float-right" href="{% url 'species-update' species.pk %}" role="button">Update Species</a>
        </div>
      </div>
      <i>{{species.author}}</i> 
      <h4><i>{{ species.source }}</i></h4>
      <p><strong>Family:</strong> {{ species.family }}</p>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-12" style="margin-left:20px;margin-right:20px;width:100%">
          <p><strong>Sources for this Species</strong></p>
          {% if species.sources.all|length > 0 %}
            <div class="table-responsive" style="padding-right: 50px;">
              <table class="table table-condensed" cellspacing=10>
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Supplier</th>
                    <th>Reference</th>
                    <th>Seed Count</th>
                    <th>End Count</th>
                    <th>Status</th>
                    <th>Date Sown</th>
                  </tr>
                </thead>
                <tbody>
                  {% for source in species.sources.all %}
                    <tr>
                      <td><p><a href="/catalogue/source/{{ source.pk }}"><strong>{{ source.name }}</strong></a></p></td>
                      <td>{{ source.obtained_from }}</td>
                      <td>{{ source.supplier_reference }}</td>
                      <td>{{ source.seed_count }}</td>
                      <td>{{ source.end_count }}</td>
                      <td>{{ source.get_status_display }}</td>
                      <td>{{ source.date_sown }}</td>
                    </tr>
                  {% endfor %}          
                </tbody>    
              </table>
            </div>
          {% else %}
            <p>There are no Sources for this Species</p>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <p><strong>Genus:</strong> {{ species.genus }}</p>
        </div>
        <div class="col-md-3">
          <p><strong>Specific Epithet:</strong> {{ species.specific_epithet }}</p>
        </div>
        <div class="col-md-6">
          <p><strong>Common Names:</strong> {{ species.commonname_set.all|join:", " }}</p> 
          {% if species.commonname.set.all|length > 0 %}
            <p><strong>Common Names:</strong> {{ species.commonname_set.all|join:", " }}</p> 
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p><strong>Llifle: </strong><a href="{{ species.url }}">{{ species.url }}</a></p> 
        </div>
      </div>
      <div class="row justify-content-between" style="margin-left:5px;margin-right:5px;margin-bottom:10px;">
        <div class="col-md-6"> 
          <div id="map" style="width: 100%; height: 500px;"></div>
        </div>
        <div class="col-md-6">
          {% for photo in species.photos.all %}
            {% if forloop.first %}
              <div style="width: 100%;">
                <a href ="/media/{{ photo.image }}"><img src="{{ photo.image.crop.500x500 }}"  alt="Card image cap" style="max-width:100%;"></a>
                <p style="width: 95%; text-align: center;"><small><i>{{ photo.caption }}</i></small></p>
              </div>
            {% endif %}
          {% endfor %}
        </div>
        <div class="row justify-content-center" style="margin-left:20px;margin-right:20px;margin-top:10px;">
          {% for photo in species.photos.all %}
            {% if not forloop.first %}
              <div class="card" style="width: 15rem;">
                <a href ="/media/{{ photo.image }}"><img class="card-img-top" src="{{ photo.image.crop.200x200 }}"  alt="Card image cap"></a>
                <div class="card-body">
                  <p style="width: 100%; text-align: center;"><small><i>{{ photo.caption }}</i></small></p>
                </div>
              </div>
              {% if forloop.counter|add:"-1"|divisibleby:4 %}
                </div>
                <div class="row  justify-content-center" style="margin-left:20px;margin-right:20px;margin-top:10px;">
              {% endif %}
            {%endif%} 
          {% endfor %}
      </div>
      <div class="row">
        <hr>
        <div class="col-md-12" style="margin-left:20px;margin-right:20px;width:100%">         
          {% for description in species.speciesdescription_set.all %}
          <p><strong>{{description.descript_type}}:</strong> {{description.description|safe}}</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyDkrygpZXzJxvajC9zqbv5eKT6HFZqLx5U"></script>

<script type="text/javascript">
  var locations = {{ locations|safe }};
  if (locations[0]) {
    var map_centre_lat = locations[0][1];
    var map_centre_long = locations[0][2];
  } else {
    var map_centre_lat =  47.071876;
    var map_centre_long =  15.441456;
  };
  

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 5,
    center: new google.maps.LatLng(map_centre_lat, map_centre_long),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  var infowindow = new google.maps.InfoWindow();

  var marker, i;

  for (i = 0; i < locations.length; i++) {
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(locations[i][1], locations[i][2]),
      map: map
    });

    google.maps.event.addListener(marker, 'click', (function(marker, i) {
      return function() {
        infowindow.setContent(locations[i][0]);
        infowindow.open(map, marker);
      }
    })(marker, i));
  }
</script>
{% endblock %}